name: SRD CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ master ]

jobs:
  MacOS-11_0:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
